pipeline:
  Build:
    image: alpine:latest
    commands:
      - echo "Test Message from agent"

  Publish:
    image: alpine:latest
    commands:
      - echo "Show env vars "
      - env
    secrets: [ docker_username, my_test, gold ]

  sonar:
    image: walmartdigital.azurecr.io/sonar-scanner-drone-plugin
    project_key: default:dronetest
    sources_directory: app
    environment:
      - SONAR_HOST=https://sonar.tools-aqchca.walmartdigital.cl
    secrets: [sonar_token]
  
    