pipeline:
  Build:
    image: alpine:latest
    commands:
      - echo "Test Message from agent"

  Publish:
    image: alpine:latest
    commands:
      - echo "end of Build"
      - echo $MY_TEST
      - echo $GOLD
    secrets: [ docker_username, my_test, gold ]

  sonar:
    image: alpine:latest
    commands:
      - echo "end of Build"
  
    