pipeline:
  Build:
    image: alpine:latest
    commands:
      - echo "Test Message"

  Publish:
    image: alpine:latest
    commands:
      - echo "end of Build"
    secrets: [ docker_username, docker_password ]
  
    