pipeline:
  Build:
    image: alpine:latest
    commands:
      - echo "Test Message from agent"

  Publish:
    image: alpine:latest
    commands:
      - echo "end of Build"
      - echo $my_test
    secrets: [ docker_username, my_test ]

  sonar:
    image: alpine:latest
    commands:
      - echo "end of Build"
  
    