pipeline:
  Build:
    image: alpine:latest
    commands:
      - echo "Test Message from agent"

  Publish:
    image: alpine:latest
    commands:
      - echo "end of Build"
    secrets: [ docker_username, docker_password ]

  # sonar:
  #   image: alpine:latest
  #   commands:
  #     - echo "end of Build"
  
    