pipeline:
  Build:
    image: alpine:latest
    commands:
      - echo "Test Message from agent"

  Publish:
    image: alpine:latest
    commands:
      - echo "end of Build"
      - echo $MY_TEST
      - echo $GOLD
    secrets: [ docker_username, my_test, gold ]

  sonar:
    image: walmartdigital.azurecr.io/sonar-scanner-drone-plugin
    project_key: default/drone-test
    sources_directory: app
    sonar_host: https://sonar.tools-aqchca.walmartdigital.cl
    secrets: [sonar_token]
  
    